"""Section 37/38 — export the trained encoder for ESP32-S3 and build hardware test vectors.

Deployment backend: plain C float32 kernels (esp32/firmware/main/encoder.c) — weights are exported
as C arrays; ONNX + TorchScript copies are kept in exported_models/ for archival/other runtimes.

Outputs
  exported_models/encoder_d{d}.onnx, encoder_d{d}.pt            (Task-AE, fold F, seed 0)
  esp32/model/model_d{d}.c                                      (weights, consumed by firmware)
  esp32/model/preproc_fold{F}.c                                 (Hann window, mel filterbank, mu, sigma)
  esp32/model/test_vectors.c                                    (N_EMBED vectors embedded for on-board self-check)
  hardware_test_vectors/sample_XXX/{input_audio.npy,input_logmel.npy,expected_latent_float.npy,
                                    expected_latent_int8.bin,metadata.json}
"""
from __future__ import annotations

import argparse
import shutil

import librosa
import numpy as np
import pandas as pd
import torch

from audio import load_fixed
from dataset import load_fold, load_norm
from evaluate import load_codec
from features import MEL_CFG, logmel, normalize
from quantizer import quantize
from utils import ROOT, save_json

EXPORT_DIR = ROOT / "exported_models"
ESP_MODEL = ROOT / "esp32" / "model"
TV_DIR = ROOT / "hardware_test_vectors"
N_EMBED = 10


def c_array(name: str, arr: np.ndarray, ctype: str = "float") -> str:
    flat = np.asarray(arr).ravel()
    if ctype == "float":
        vals = []
        for v in flat.astype(np.float32):
            t = f"{v:.9g}"
            vals.append((t if any(c in t for c in ".e") else t + ".0") + "f")
    else:
        vals = [str(int(v)) for v in flat]
    lines = [", ".join(vals[i:i + 8]) for i in range(0, len(vals), 8)]
    return f"const {ctype} {name}[{len(flat)}] = {{\n  " + ",\n  ".join(lines) + "\n};\n"


def export_model(method: str, d: int, fold: int, seed: int) -> dict:
    name = f"{method}_d{d}_fold{fold}_seed{seed}"
    codec = load_codec(name)
    enc = codec.encoder.eval()
    EXPORT_DIR.mkdir(exist_ok=True)
    torch.save(enc.state_dict(), EXPORT_DIR / f"encoder_d{d}.pt")
    try:
        torch.onnx.export(enc, torch.zeros(1, 1, 64, 32), EXPORT_DIR / f"encoder_d{d}.onnx",
                          input_names=["logmel"], output_names=["z"], opset_version=17, dynamo=False)
        onnx_ok = True
    except Exception as e:  # onnx package missing etc. — C export below is what the firmware uses
        print("ONNX export skipped:", e)
        onnx_ok = False
    convs = [m for m in enc.net if isinstance(m, torch.nn.Conv2d)]
    parts = [f"// Auto-generated by src/export_encoder.py from checkpoints/codecs/{name}.pt\n",
             '#include "model.h"\n\n']
    n_params = 0
    for i, c in enumerate(convs):
        parts.append(c_array(f"ENC_W{i}", c.weight.detach().numpy()))
        parts.append(c_array(f"ENC_B{i}", c.bias.detach().numpy()))
        n_params += c.weight.numel() + c.bias.numel()
    parts.append(f'const int ENC_R = {codec.r};\nconst int ENC_D = {d};\nconst char ENC_NAME[] = "{name}";\n'
                 f"const int ENC_N_PARAMS = {n_params};\n")
    ESP_MODEL.mkdir(parents=True, exist_ok=True)
    (ESP_MODEL / f"model_d{d}.c").write_text("".join(parts))
    return dict(name=name, d=d, r=codec.r, n_params=n_params, weight_bytes_fp32=4 * n_params, onnx=onnx_ok)


def export_preproc(fold: int) -> None:
    window = librosa.filters.get_window("hann", MEL_CFG["n_fft"], fftbins=True)
    fb = librosa.filters.mel(sr=MEL_CFG["sr"], n_fft=MEL_CFG["n_fft"], n_mels=MEL_CFG["n_mels"],
                             fmin=MEL_CFG["fmin"], fmax=MEL_CFG["fmax"], htk=MEL_CFG["htk"], norm=MEL_CFG["norm"])
    mu, sigma = load_norm(fold)
    src = [f"// Auto-generated by src/export_encoder.py — preprocessing constants (fold {fold} Train stats)\n",
           '#include "model.h"\n\n', c_array("PRE_HANN", window), c_array("PRE_MELFB", fb),
           c_array("PRE_MU", mu), c_array("PRE_SIGMA", sigma), f"const int PRE_FOLD = {fold};\n"]
    (ESP_MODEL / f"preproc_fold{fold}.c").write_text("".join(src))


def build_test_vectors(fold: int, seed: int, ds) -> None:
    """20 vectors: 2 per digit, cycling over all 6 speakers (consistency check, not accuracy)."""
    man = pd.read_csv(ROOT / "data" / "manifest.csv")
    spk = sorted(man.speaker.unique())
    picks = []
    for dig in range(10):
        for k in range(2):
            s = spk[(2 * dig + k) % len(spk)]
            picks.append(man[(man.label == dig) & (man.speaker == s)].sort_values("recording_index").iloc[5])
    mu, sigma = load_norm(fold)
    codecs = {d: load_codec(f"Task-AE_d{d}_fold{fold}_seed{seed}") for d in ds}
    if TV_DIR.exists():
        shutil.rmtree(TV_DIR)
    audio_all, x_all, q_all = [], [], {d: [] for d in ds}
    for i, r in enumerate(picks):
        out = TV_DIR / f"sample_{i:03d}"
        out.mkdir(parents=True)
        a = load_fixed(ROOT / r.path)
        x = normalize(logmel(a), mu, sigma)
        np.save(out / "input_audio.npy", a)
        np.save(out / "input_logmel.npy", x)
        meta = dict(filename=r.filename, label=int(r.label), speaker=r.speaker, fold=fold, seed=seed,
                    input="normalised log-mel 1x64x32 float32 (fold Train stats)", models={})
        lat_f = {}
        for d, c in codecs.items():
            with torch.no_grad():
                z = c.encoder(torch.from_numpy(x)[None, None])
            q = quantize(z).numpy().reshape(-1)
            lat_f[f"d{d}"] = z.numpy().reshape(-1)
            (out / f"expected_latent_int8_d{d}.bin").write_bytes(q.tobytes())
            q_all[d].append(q)
            meta["models"][f"d{d}"] = f"Task-AE_d{d}_fold{fold}_seed{seed}"
        np.save(out / "expected_latent_float.npy", lat_f["d128"] if "d128" in lat_f else next(iter(lat_f.values())))
        np.savez(out / "expected_latent_float_all.npz", **lat_f)
        if 128 in codecs:
            shutil.copy(out / "expected_latent_int8_d128.bin", out / "expected_latent_int8.bin")
        save_json(meta, out / "metadata.json")
        audio_all.append(a)
        x_all.append(x)
    # Embedded subset for the firmware self-check
    src = ["// Auto-generated by src/export_encoder.py — embedded test vectors\n", '#include "model.h"\n\n',
           f"const int TV_N = {N_EMBED};\n",
           c_array("TV_AUDIO", np.stack(audio_all[:N_EMBED])), c_array("TV_LOGMEL", np.stack(x_all[:N_EMBED])),
           c_array("TV_LABEL", np.array([int(p.label) for p in picks[:N_EMBED]]), "int")]
    for d in (64, 128, 256):  # placeholders keep the firmware linkable when a d was not exported
        q = np.stack(q_all[d][:N_EMBED]) if d in ds else np.zeros(1, np.int8)
        src.append(c_array(f"TV_Q_D{d}", q, "signed char"))
    (ESP_MODEL / "test_vectors.c").write_text("".join(src))
    pd.DataFrame([dict(sample=f"sample_{i:03d}", filename=p.filename, label=int(p.label), speaker=p.speaker,
                       embedded_in_firmware=i < N_EMBED) for i, p in enumerate(picks)]).to_csv(TV_DIR / "index.csv", index=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fold", type=int, default=1)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--ds", type=int, nargs="+", default=[64, 128, 256])
    a = ap.parse_args()
    info = [export_model("Task-AE", d, a.fold, a.seed) for d in a.ds]
    export_preproc(a.fold)
    build_test_vectors(a.fold, a.seed, a.ds)
    save_json({"exports": info, "fold": a.fold, "seed": a.seed, "backend": "plain C float32 (esp32/firmware/main/encoder.c)"},
              EXPORT_DIR / "export_info.json")
    print(pd.DataFrame(info).to_string(index=False))


if __name__ == "__main__":
    main()
